server:
  protocol: "http://"
  address: 127.0.0.1
  port: 8080
  radmin:
    address: ${RADMIN_ADDRESS}
  error:
    include-stacktrace: never
  servlet:
    context-path: /api


frontend:
  address: "http://127.0.0.1:5500"
  paths:
    authorized: "/login/authorized"
    activate-account: "/login/activate-account"
    a2f: "/login/a2f"


spring:
  config:
    import: application.yaml
    name: chatPG
  datasource:
    url: ${CHATPG_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  ai:
    google:
      genai:
        project-id: ${GOOGLE_CLOUD_PROJECT}
        location: southamerica-east1
    chutes:
      llm:
        url: https://llm.chutes.ai/v1/chat/completions
        api-key: ${CHUTES_API_KEY}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CHATPG_EMAIL_ADDRESS}
    password: ${CHATPG_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /doc
    enabled: true
  swagger-ui:
    path: /doc/swagger-ui.html


hibernate:
  dialect: org.hibernate.dialect.HSQLDialect


logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type.descriptor.sql.BasicBinder: WARN
      springframework:
        web:
          servlet:
            handler:
              AbstractHandlerExceptionResolver: ERROR
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: ERROR

security:
  http.cookie.secure: false
  bcrypt-password-strength: 10
  token:
    secret: ${API_SECURITY_KEY_SECRET}
    access-expires-in: 15m
    refresh-expires-in: 7d
  request-handle:
    activate-account-expires-in: 30m
    change-password-expires-in: 15m
    a2f-expires-in: 1m
    login-with-handle-expires-in: 1m
  auth.external:
    github.client:
      id: ${GITHUB_CLIENT_ID}
      secret: ${GITHUB_CLIENT_SECRET}
    google.client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
