package com.yourRPG.chatPG.service.ai

import com.yourRPG.chatPG.service.ai.providers.AiModel
import com.yourRPG.chatPG.service.ai.providers.AiProvider

interface IResponsive {

    fun getProvider(): AiProvider

    /**
     * Returns the text generated by the model specified for the given prompt.
     *
     * @param [model] the AI model.
     * @param [prompt] the [String] containing the text to be prompted.
     * @return [String] nullable, since some providers are able to return a null response to some peculiar prompts.
     * @throws com.yourRPG.chatPG.exception.ai.models.UnavailableAiException if the response for the request was not valid,
     * likely because the response was an error object and not a response object.
     *  Therefore, it can be detected by first catching an [com.fasterxml.jackson.databind.exc.MismatchedInputException],
     * and then throwing the intended one.
     */
    fun askAi(model: AiModel, prompt: String): String?

}